version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "8082:80"
    restart: always
    networks:
      - pub-crawl_default

  backend:
    environment:
      - PYTHONUNBUFFERED=1
    build: ./flask-backend
    ports:
      - "8001:8001"
    restart: always
    env_file: .env
    networks:
      - pub-crawl_default

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: always
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    # The tunnel needs to be on the same network as the apps AND Nginx
    networks:
      - pub-crawl_default
      - csc2033_team32_25-26_default

networks:
  pub-crawl_default:
    external: true
  csc2033_team32_25-26_default:
    external: true
